var arr=	[
  "Is your ass jealous of the amount of shit that just came out of your mouth?",
  "Two wrongs don't make a right, take your parents as an example.",
  "I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
  "Wife: \"I look fat. Can you give me a compliment?\" Husband: \"You have perfect eyesight.\"",
  "If I wanted to kill myself I'd climb your ego and jump to your IQ.",
  "Your family tree must be a cactus because everybody on it is a prick.",
  "Your birth certificate is an apology letter from the condom factory.",
  "Yo're so ugly, when your mom dropped you off at school she got a fine for littering.",
  "Don't you love nature, despite what it did to you?",
  "You must have been born on a highway because that's where most accidents happen.",   "The only way you'll ever get laid is if you crawl up a chicken's ass and wait.",
  "It's better to let someone think you are an Idiot than to open your mouth and prove it.",
  "Keep talking, someday you'll say something intelligent!",
  "If you really want to know about mistakes, you should ask your parents.",
  "I wasn't born with enough middle fingers to let you know how I feel about you.",
  "What language are you speaking? Cause it sounds like bullshit.",
  "If I had a face like yours, I'd sue my parents.",
  "If laughter is the best medicine, your face must be curing the world.",
  "You so ugly when who were born the doctor threw you out the window and the window threw you back.",
  "You're so ugly, you scared the crap out of the toilet.",  "Roses are red violets are blue, God made me pretty, what happened to you?",
  "You're the reason the gene pool needs a lifeguard.",
  "Hey, you have something on your chin... no, the 3rd one down.",
  "I love what you've done with your hair. How do you get it to come out of the nostrils like that?",
  "You do realize makeup isn't going to fix your stupidity?",
  "We all sprang from apes, but you didn't spring far enough.",
  "Which sexual position produces the ugliest children? Ask your mother.",
  "If bullshit could float...you'd be the Admiral of the fleet! ",
  "Ever since I saw you in your family tree I've wanted to cut it down.",
  "You're so fake, Barbie is jealous.",  "You are proof that evolution CAN go in reverse.",
  "Ordinarily people live and learn. You just live.",
  "Do you wanna lose ten pounds of ugly fat? Cut off your head.",
  "I'm jealous of all the people that haven't met you!",
  "Aha, I see the Fuck-Up Fairy has visited us again! ",
  "So, a thought crossed your mind? Must have been a long and lonely journey.",
  "There's only one problem with your face, I can see it.",
  "Karma takes too long, I'd rather beat the shit out of you just now.",
  "Whats the difference between your girlfriend and a walrus? One has a moustache and smells of fish and the other is a walrus.",
  "It looks like your face caught on fire and someone tried to put it out with a hammer.",  "As an outsider, what do you think of the human race?",
  "I'm glad to see you're not letting your education get in the way of your ignorance.",
  "Support bacteria - they're the only culture some people have.",
  "I don't know what makes you so stupid, but it really works.",
  "Calling you an idiot would be an insult to all stupid people.",
  "I don't think you are stupid. You just have a bad luck when thinking.",
  "I'd like to see things from your point of view, but I can't seem to get my head that far up your ass.",
  "I would ask you how old you are but I know you can't count that high.",
  "You look like a before picture.",
  "You are so ugly when you looked in the mirror your reflection walked away.","Is your ass jealous of the amount of shit that just came out of your mouth?",
  "Two wrongs don't make a right, take your parents as an example.",
  "I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
  "Wife: \"I look fat. Can you give me a compliment?\" Husband: \"You have perfect eyesight.\"",
  "If I wanted to kill myself I'd climb your ego and jump to your IQ.",
  "Your family tree must be a cactus because everybody on it is a prick.",
  "Your birth certificate is an apology letter from the condom factory.",
  "Yo're so ugly, when your mom dropped you off at school she got a fine for littering.",
  "Don't you love nature, despite what it did to you?",
  "You must have been born on a highway because that's where most accidents happen.",   "The only way you'll ever get laid is if you crawl up a chicken's ass and wait.",
  "It's better to let someone think you are an Idiot than to open your mouth and prove it.",
  "Keep talking, someday you'll say something intelligent!",
  "If you really want to know about mistakes, you should ask your parents.",
  "I wasn't born with enough middle fingers to let you know how I feel about you.",
  "What language are you speaking? Cause it sounds like bullshit.",
  "If I had a face like yours, I'd sue my parents.",
  "If laughter is the best medicine, your face must be curing the world.",
  "You so ugly when who were born the doctor threw you out the window and the window threw you back.",
  "You're so ugly, you scared the crap out of the toilet.",  "Roses are red violets are blue, God made me pretty, what happened to you?",
  "You're the reason the gene pool needs a lifeguard.",
  "Hey, you have something on your chin... no, the 3rd one down.",
  "I love what you've done with your hair. How do you get it to come out of the nostrils like that?",
  "You do realize makeup isn't going to fix your stupidity?",
  "We all sprang from apes, but you didn't spring far enough.",
  "Which sexual position produces the ugliest children? Ask your mother.",
  "If bullshit could float...you'd be the Admiral of the fleet! ",
  "Ever since I saw you in your family tree I've wanted to cut it down.",
  "You're so fake, Barbie is jealous.",  "You are proof that evolution CAN go in reverse.",
  "Ordinarily people live and learn. You just live.",
  "Do you wanna lose ten pounds of ugly fat? Cut off your head.",
  "I'm jealous of all the people that haven't met you!",
  "Aha, I see the Fuck-Up Fairy has visited us again! ",
  "So, a thought crossed your mind? Must have been a long and lonely journey.",
  "There's only one problem with your face, I can see it.",
  "Karma takes too long, I'd rather beat the shit out of you just now.",
  "Whats the difference between your girlfriend and a walrus? One has a moustache and smells of fish and the other is a walrus.",
  "It looks like your face caught on fire and someone tried to put it out with a hammer.",  "As an outsider, what do you think of the human race?",
  "I'm glad to see you're not letting your education get in the way of your ignorance.",
  "Support bacteria - they're the only culture some people have.",
  "I don't know what makes you so stupid, but it really works.",
  "Calling you an idiot would be an insult to all stupid people.",
  "I don't think you are stupid. You just have a bad luck when thinking.",
  "I'd like to see things from your point of view, but I can't seem to get my head that far up your ass.",
  "I would ask you how old you are but I know you can't count that high.",
  "You look like a before picture.",
  "You are so ugly when you looked in the mirror your reflection walked away.","Is your ass jealous of the amount of shit that just came out of your mouth?",
  "Two wrongs don't make a right, take your parents as an example.",
  "I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
  "Wife: \"I look fat. Can you give me a compliment?\" Husband: \"You have perfect eyesight.\"",
  "If I wanted to kill myself I'd climb your ego and jump to your IQ.",
  "Your family tree must be a cactus because everybody on it is a prick.",
  "Your birth certificate is an apology letter from the condom factory.",
  "Yo're so ugly, when your mom dropped you off at school she got a fine for littering.",
  "Don't you love nature, despite what it did to you?",
  "You must have been born on a highway because that's where most accidents happen.",   "The only way you'll ever get laid is if you crawl up a chicken's ass and wait.",
  "It's better to let someone think you are an Idiot than to open your mouth and prove it.",
  "Keep talking, someday you'll say something intelligent!",
  "If you really want to know about mistakes, you should ask your parents.",
  "I wasn't born with enough middle fingers to let you know how I feel about you.",
  "What language are you speaking? Cause it sounds like bullshit.",
  "If I had a face like yours, I'd sue my parents.",
  "If laughter is the best medicine, your face must be curing the world.",
  "You so ugly when who were born the doctor threw you out the window and the window threw you back.",
  "You're so ugly, you scared the crap out of the toilet.",  "Roses are red violets are blue, God made me pretty, what happened to you?",
  "You're the reason the gene pool needs a lifeguard.",
  "Hey, you have something on your chin... no, the 3rd one down.",
  "I love what you've done with your hair. How do you get it to come out of the nostrils like that?",
  "You do realize makeup isn't going to fix your stupidity?",
  "We all sprang from apes, but you didn't spring far enough.",
  "Which sexual position produces the ugliest children? Ask your mother.",
  "If bullshit could float...you'd be the Admiral of the fleet! ",
  "Ever since I saw you in your family tree I've wanted to cut it down.",
  "You're so fake, Barbie is jealous.",  "You are proof that evolution CAN go in reverse.",
  "Ordinarily people live and learn. You just live.",
  "Do you wanna lose ten pounds of ugly fat? Cut off your head.",
  "I'm jealous of all the people that haven't met you!",
  "Aha, I see the Fuck-Up Fairy has visited us again! ",
  "So, a thought crossed your mind? Must have been a long and lonely journey.",
  "There's only one problem with your face, I can see it.",
  "Karma takes too long, I'd rather beat the shit out of you just now.",
  "Whats the difference between your girlfriend and a walrus? One has a moustache and smells of fish and the other is a walrus.",
  "It looks like your face caught on fire and someone tried to put it out with a hammer.",  "As an outsider, what do you think of the human race?",
  "I'm glad to see you're not letting your education get in the way of your ignorance.",
  "Support bacteria - they're the only culture some people have.",
  "I don't know what makes you so stupid, but it really works.",
  "Calling you an idiot would be an insult to all stupid people.",
  "I don't think you are stupid. You just have a bad luck when thinking.",
  "I'd like to see things from your point of view, but I can't seem to get my head that far up your ass.",
  "I would ask you how old you are but I know you can't count that high.",
  "You look like a before picture.",
  "You are so ugly when you looked in the mirror your reflection walked away.","Is your ass jealous of the amount of shit that just came out of your mouth?",
  "Two wrongs don't make a right, take your parents as an example.",
  "I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
  "Wife: \"I look fat. Can you give me a compliment?\" Husband: \"You have perfect eyesight.\"",
  "If I wanted to kill myself I'd climb your ego and jump to your IQ.",
  "Your family tree must be a cactus because everybody on it is a prick.",
  "Your birth certificate is an apology letter from the condom factory.",
  "Yo're so ugly, when your mom dropped you off at school she got a fine for littering.",
  "Don't you love nature, despite what it did to you?",
  "You must have been born on a highway because that's where most accidents happen.",   "The only way you'll ever get laid is if you crawl up a chicken's ass and wait.",
  "It's better to let someone think you are an Idiot than to open your mouth and prove it.",
  "Keep talking, someday you'll say something intelligent!",
  "If you really want to know about mistakes, you should ask your parents.",
  "I wasn't born with enough middle fingers to let you know how I feel about you.",
  "What language are you speaking? Cause it sounds like bullshit.",
  "If I had a face like yours, I'd sue my parents.",
  "If laughter is the best medicine, your face must be curing the world.",
  "You so ugly when who were born the doctor threw you out the window and the window threw you back.",
  "You're so ugly, you scared the crap out of the toilet.",  "Roses are red violets are blue, God made me pretty, what happened to you?",
  "You're the reason the gene pool needs a lifeguard.",
  "Hey, you have something on your chin... no, the 3rd one down.",
  "I love what you've done with your hair. How do you get it to come out of the nostrils like that?",
  "You do realize makeup isn't going to fix your stupidity?",
  "We all sprang from apes, but you didn't spring far enough.",
  "Which sexual position produces the ugliest children? Ask your mother.",
  "If bullshit could float...you'd be the Admiral of the fleet! ",
  "Ever since I saw you in your family tree I've wanted to cut it down.",
  "You're so fake, Barbie is jealous.",  "You are proof that evolution CAN go in reverse.",
  "Ordinarily people live and learn. You just live.",
  "Do you wanna lose ten pounds of ugly fat? Cut off your head.",
  "I'm jealous of all the people that haven't met you!",
  "Aha, I see the Fuck-Up Fairy has visited us again! ",
  "So, a thought crossed your mind? Must have been a long and lonely journey.",
  "There's only one problem with your face, I can see it.",
  "Karma takes too long, I'd rather beat the shit out of you just now.",
  "Whats the difference between your girlfriend and a walrus? One has a moustache and smells of fish and the other is a walrus.",
  "It looks like your face caught on fire and someone tried to put it out with a hammer.",  "As an outsider, what do you think of the human race?",
  "I'm glad to see you're not letting your education get in the way of your ignorance.",
  "Support bacteria - they're the only culture some people have.",
  "I don't know what makes you so stupid, but it really works.",
  "Calling you an idiot would be an insult to all stupid people.",
  "I don't think you are stupid. You just have a bad luck when thinking.",
  "I'd like to see things from your point of view, but I can't seem to get my head that far up your ass.",
  "I would ask you how old you are but I know you can't count that high.",
  "You look like a before picture.",
  "You are so ugly when you looked in the mirror your reflection walked away.","Is your ass jealous of the amount of shit that just came out of your mouth?",
  "Two wrongs don't make a right, take your parents as an example.",
  "I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
  "Wife: \"I look fat. Can you give me a compliment?\" Husband: \"You have perfect eyesight.\"",
  "If I wanted to kill myself I'd climb your ego and jump to your IQ.",
  "Your family tree must be a cactus because everybody on it is a prick.",
  "Your birth certificate is an apology letter from the condom factory.",
  "Yo're so ugly, when your mom dropped you off at school she got a fine for littering.",
  "Don't you love nature, despite what it did to you?",
  "You must have been born on a highway because that's where most accidents happen.",   "The only way you'll ever get laid is if you crawl up a chicken's ass and wait.",
  "It's better to let someone think you are an Idiot than to open your mouth and prove it.",
  "Keep talking, someday you'll say something intelligent!",
  "If you really want to know about mistakes, you should ask your parents.",
  "I wasn't born with enough middle fingers to let you know how I feel about you.",
  "What language are you speaking? Cause it sounds like bullshit.",
  "If I had a face like yours, I'd sue my parents.",
  "If laughter is the best medicine, your face must be curing the world.",
  "You so ugly when who were born the doctor threw you out the window and the window threw you back.",
  "You're so ugly, you scared the crap out of the toilet.",  "Roses are red violets are blue, God made me pretty, what happened to you?",
  "You're the reason the gene pool needs a lifeguard.",
  "Hey, you have something on your chin... no, the 3rd one down.",
  "I love what you've done with your hair. How do you get it to come out of the nostrils like that?",
  "You do realize makeup isn't going to fix your stupidity?",
  "We all sprang from apes, but you didn't spring far enough.",
  "Which sexual position produces the ugliest children? Ask your mother.",
  "If bullshit could float...you'd be the Admiral of the fleet! ",
  "Ever since I saw you in your family tree I've wanted to cut it down.",
  "You're so fake, Barbie is jealous.",  "You are proof that evolution CAN go in reverse.",
  "Ordinarily people live and learn. You just live.",
  "Do you wanna lose ten pounds of ugly fat? Cut off your head.",
  "I'm jealous of all the people that haven't met you!",
  "Aha, I see the Fuck-Up Fairy has visited us again! ",
  "So, a thought crossed your mind? Must have been a long and lonely journey.",
  "There's only one problem with your face, I can see it.",
  "Karma takes too long, I'd rather beat the shit out of you just now.",
  "Whats the difference between your girlfriend and a walrus? One has a moustache and smells of fish and the other is a walrus.",
  "It looks like your face caught on fire and someone tried to put it out with a hammer.",  "As an outsider, what do you think of the human race?",
  "I'm glad to see you're not letting your education get in the way of your ignorance.",
  "Support bacteria - they're the only culture some people have.",
  "I don't know what makes you so stupid, but it really works.",
  "Calling you an idiot would be an insult to all stupid people.",
  "I don't think you are stupid. You just have a bad luck when thinking.",
  "I'd like to see things from your point of view, but I can't seem to get my head that far up your ass.",
  "I would ask you how old you are but I know you can't count that high.",
  "You look like a before picture.",
  "You are so ugly when you looked in the mirror your reflection walked away.","Is your ass jealous of the amount of shit that just came out of your mouth?",
  "Two wrongs don't make a right, take your parents as an example.",
  "I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
  "Wife: \"I look fat. Can you give me a compliment?\" Husband: \"You have perfect eyesight.\"",
  "If I wanted to kill myself I'd climb your ego and jump to your IQ.",
  "Your family tree must be a cactus because everybody on it is a prick.",
  "Your birth certificate is an apology letter from the condom factory.",
  "Yo're so ugly, when your mom dropped you off at school she got a fine for littering.",
  "Don't you love nature, despite what it did to you?",
  "You must have been born on a highway because that's where most accidents happen.",   "The only way you'll ever get laid is if you crawl up a chicken's ass and wait.",
  "It's better to let someone think you are an Idiot than to open your mouth and prove it.",
  "Keep talking, someday you'll say something intelligent!",
  "If you really want to know about mistakes, you should ask your parents.",
  "I wasn't born with enough middle fingers to let you know how I feel about you.",
  "What language are you speaking? Cause it sounds like bullshit.",
  "If I had a face like yours, I'd sue my parents.",
  "If laughter is the best medicine, your face must be curing the world.",
  "You so ugly when who were born the doctor threw you out the window and the window threw you back.",
  "You're so ugly, you scared the crap out of the toilet.",  "Roses are red violets are blue, God made me pretty, what happened to you?",
  "You're the reason the gene pool needs a lifeguard.",
  "Hey, you have something on your chin... no, the 3rd one down.",
  "I love what you've done with your hair. How do you get it to come out of the nostrils like that?",
  "You do realize makeup isn't going to fix your stupidity?",
  "We all sprang from apes, but you didn't spring far enough.",
  "Which sexual position produces the ugliest children? Ask your mother.",
  "If bullshit could float...you'd be the Admiral of the fleet! ",
  "Ever since I saw you in your family tree I've wanted to cut it down.",
  "You're so fake, Barbie is jealous.",  "You are proof that evolution CAN go in reverse.",
  "Ordinarily people live and learn. You just live.",
  "Do you wanna lose ten pounds of ugly fat? Cut off your head.",
  "I'm jealous of all the people that haven't met you!",
  "Aha, I see the Fuck-Up Fairy has visited us again! ",
  "So, a thought crossed your mind? Must have been a long and lonely journey.",
  "There's only one problem with your face, I can see it.",
  "Karma takes too long, I'd rather beat the shit out of you just now.",
  "Whats the difference between your girlfriend and a walrus? One has a moustache and smells of fish and the other is a walrus.",
  "It looks like your face caught on fire and someone tried to put it out with a hammer.",  "As an outsider, what do you think of the human race?",
  "I'm glad to see you're not letting your education get in the way of your ignorance.",
  "Support bacteria - they're the only culture some people have.",
  "I don't know what makes you so stupid, but it really works.",
  "Calling you an idiot would be an insult to all stupid people.",
  "I don't think you are stupid. You just have a bad luck when thinking.",
  "I'd like to see things from your point of view, but I can't seem to get my head that far up your ass.",
  "I would ask you how old you are but I know you can't count that high.",
  "You look like a before picture.",
  "You are so ugly when you looked in the mirror your reflection walked away.","Is your ass jealous of the amount of shit that just came out of your mouth?",
  "Two wrongs don't make a right, take your parents as an example.",
  "I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
  "Wife: \"I look fat. Can you give me a compliment?\" Husband: \"You have perfect eyesight.\"",
  "If I wanted to kill myself I'd climb your ego and jump to your IQ.",
  "Your family tree must be a cactus because everybody on it is a prick.",
  "Your birth certificate is an apology letter from the condom factory.",
  "Yo're so ugly, when your mom dropped you off at school she got a fine for littering.",
  "Don't you love nature, despite what it did to you?",
  "You must have been born on a highway because that's where most accidents happen.",   "The only way you'll ever get laid is if you crawl up a chicken's ass and wait.",
  "It's better to let someone think you are an Idiot than to open your mouth and prove it.",
  "Keep talking, someday you'll say something intelligent!",
  "If you really want to know about mistakes, you should ask your parents.",
  "I wasn't born with enough middle fingers to let you know how I feel about you.",
  "What language are you speaking? Cause it sounds like bullshit.",
  "If I had a face like yours, I'd sue my parents.",
  "If laughter is the best medicine, your face must be curing the world.",
  "You so ugly when who were born the doctor threw you out the window and the window threw you back.",
  "You're so ugly, you scared the crap out of the toilet.",  "Roses are red violets are blue, God made me pretty, what happened to you?",
  "You're the reason the gene pool needs a lifeguard.",
  "Hey, you have something on your chin... no, the 3rd one down.",
  "I love what you've done with your hair. How do you get it to come out of the nostrils like that?",
  "You do realize makeup isn't going to fix your stupidity?",
  "We all sprang from apes, but you didn't spring far enough.",
  "Which sexual position produces the ugliest children? Ask your mother.",
  "If bullshit could float...you'd be the Admiral of the fleet! ",
  "Ever since I saw you in your family tree I've wanted to cut it down.",
  "You're so fake, Barbie is jealous.",  "You are proof that evolution CAN go in reverse.",
  "Ordinarily people live and learn. You just live.",
  "Do you wanna lose ten pounds of ugly fat? Cut off your head.",
  "I'm jealous of all the people that haven't met you!",
  "Aha, I see the Fuck-Up Fairy has visited us again! ",
  "So, a thought crossed your mind? Must have been a long and lonely journey.",
  "There's only one problem with your face, I can see it.",
  "Karma takes too long, I'd rather beat the shit out of you just now.",
  "Whats the difference between your girlfriend and a walrus? One has a moustache and smells of fish and the other is a walrus.",
  "It looks like your face caught on fire and someone tried to put it out with a hammer.",  "As an outsider, what do you think of the human race?",
  "I'm glad to see you're not letting your education get in the way of your ignorance.",
  "Support bacteria - they're the only culture some people have.",
  "I don't know what makes you so stupid, but it really works.",
  "Calling you an idiot would be an insult to all stupid people.",
  "I don't think you are stupid. You just have a bad luck when thinking.",
  "I'd like to see things from your point of view, but I can't seem to get my head that far up your ass.",
  "I would ask you how old you are but I know you can't count that high.",
  "You look like a before picture.",
  "You are so ugly when you looked in the mirror your reflection walked away.","Is your ass jealous of the amount of shit that just came out of your mouth?",
  "Two wrongs don't make a right, take your parents as an example.",
  "I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
  "Wife: \"I look fat. Can you give me a compliment?\" Husband: \"You have perfect eyesight.\"",
  "If I wanted to kill myself I'd climb your ego and jump to your IQ.",
  "Your family tree must be a cactus because everybody on it is a prick.",
  "Your birth certificate is an apology letter from the condom factory.",
  "Yo're so ugly, when your mom dropped you off at school she got a fine for littering.",
  "Don't you love nature, despite what it did to you?",
  "You must have been born on a highway because that's where most accidents happen.",   "The only way you'll ever get laid is if you crawl up a chicken's ass and wait.",
  "It's better to let someone think you are an Idiot than to open your mouth and prove it.",
  "Keep talking, someday you'll say something intelligent!",
  "If you really want to know about mistakes, you should ask your parents.",
  "I wasn't born with enough middle fingers to let you know how I feel about you.",
  "What language are you speaking? Cause it sounds like bullshit.",
  "If I had a face like yours, I'd sue my parents.",
  "If laughter is the best medicine, your face must be curing the world.",
  "You so ugly when who were born the doctor threw you out the window and the window threw you back.",
  "You're so ugly, you scared the crap out of the toilet.",  "Roses are red violets are blue, God made me pretty, what happened to you?",
  "You're the reason the gene pool needs a lifeguard.",
  "Hey, you have something on your chin... no, the 3rd one down.",
  "I love what you've done with your hair. How do you get it to come out of the nostrils like that?",
  "You do realize makeup isn't going to fix your stupidity?",
  "We all sprang from apes, but you didn't spring far enough.",
  "Which sexual position produces the ugliest children? Ask your mother.",
  "If bullshit could float...you'd be the Admiral of the fleet! ",
  "Ever since I saw you in your family tree I've wanted to cut it down.",
  "You're so fake, Barbie is jealous.",  "You are proof that evolution CAN go in reverse.",
  "Ordinarily people live and learn. You just live.",
  "Do you wanna lose ten pounds of ugly fat? Cut off your head.",
  "I'm jealous of all the people that haven't met you!",
  "Aha, I see the Fuck-Up Fairy has visited us again! ",
  "So, a thought crossed your mind? Must have been a long and lonely journey.",
  "There's only one problem with your face, I can see it.",
  "Karma takes too long, I'd rather beat the shit out of you just now.",
  "Whats the difference between your girlfriend and a walrus? One has a moustache and smells of fish and the other is a walrus.",
  "It looks like your face caught on fire and someone tried to put it out with a hammer.",  "As an outsider, what do you think of the human race?",
  "I'm glad to see you're not letting your education get in the way of your ignorance.",
  "Support bacteria - they're the only culture some people have.",
  "I don't know what makes you so stupid, but it really works.",
  "Calling you an idiot would be an insult to all stupid people.",
  "I don't think you are stupid. You just have a bad luck when thinking.",
  "I'd like to see things from your point of view, but I can't seem to get my head that far up your ass.",
  "I would ask you how old you are but I know you can't count that high.",
  "You look like a before picture.",
  "You are so ugly when you looked in the mirror your reflection walked away.","Is your ass jealous of the amount of shit that just came out of your mouth?",
  "Two wrongs don't make a right, take your parents as an example.",
  "I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
  "Wife: \"I look fat. Can you give me a compliment?\" Husband: \"You have perfect eyesight.\"",
  "If I wanted to kill myself I'd climb your ego and jump to your IQ.",
  "Your family tree must be a cactus because everybody on it is a prick.",
  "Your birth certificate is an apology letter from the condom factory.",
  "Yo're so ugly, when your mom dropped you off at school she got a fine for littering.",
  "Don't you love nature, despite what it did to you?",
  "You must have been born on a highway because that's where most accidents happen.",   "The only way you'll ever get laid is if you crawl up a chicken's ass and wait.",
  "It's better to let someone think you are an Idiot than to open your mouth and prove it.",
  "Keep talking, someday you'll say something intelligent!",
  "If you really want to know about mistakes, you should ask your parents.",
  "I wasn't born with enough middle fingers to let you know how I feel about you.",
  "What language are you speaking? Cause it sounds like bullshit.",
  "If I had a face like yours, I'd sue my parents.",
  "If laughter is the best medicine, your face must be curing the world.",
  "You so ugly when who were born the doctor threw you out the window and the window threw you back.",
  "You're so ugly, you scared the crap out of the toilet.",  "Roses are red violets are blue, God made me pretty, what happened to you?",
  "You're the reason the gene pool needs a lifeguard.",
  "Hey, you have something on your chin... no, the 3rd one down.",
  "I love what you've done with your hair. How do you get it to come out of the nostrils like that?",
  "You do realize makeup isn't going to fix your stupidity?",
  "We all sprang from apes, but you didn't spring far enough.",
  "Which sexual position produces the ugliest children? Ask your mother.",
  "If bullshit could float...you'd be the Admiral of the fleet! ",
  "Ever since I saw you in your family tree I've wanted to cut it down.",
  "You're so fake, Barbie is jealous.",  "You are proof that evolution CAN go in reverse.",
  "Ordinarily people live and learn. You just live.",
  "Do you wanna lose ten pounds of ugly fat? Cut off your head.",
  "I'm jealous of all the people that haven't met you!",
  "Aha, I see the Fuck-Up Fairy has visited us again! ",
  "So, a thought crossed your mind? Must have been a long and lonely journey.",
  "There's only one problem with your face, I can see it.",
  "Karma takes too long, I'd rather beat the shit out of you just now.",
  "Whats the difference between your girlfriend and a walrus? One has a moustache and smells of fish and the other is a walrus.",
  "It looks like your face caught on fire and someone tried to put it out with a hammer.",  "As an outsider, what do you think of the human race?",
  "I'm glad to see you're not letting your education get in the way of your ignorance.",
  "Support bacteria - they're the only culture some people have.",
  "I don't know what makes you so stupid, but it really works.",
  "Calling you an idiot would be an insult to all stupid people.",
  "I don't think you are stupid. You just have a bad luck when thinking.",
  "I'd like to see things from your point of view, but I can't seem to get my head that far up your ass.",
  "I would ask you how old you are but I know you can't count that high.",
  "You look like a before picture.",
  "You are so ugly when you looked in the mirror your reflection walked away.","Is your ass jealous of the amount of shit that just came out of your mouth?",
  "Two wrongs don't make a right, take your parents as an example.",
  "I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
  "Wife: \"I look fat. Can you give me a compliment?\" Husband: \"You have perfect eyesight.\"",
  "If I wanted to kill myself I'd climb your ego and jump to your IQ.",
  "Your family tree must be a cactus because everybody on it is a prick.",
  "Your birth certificate is an apology letter from the condom factory.",
  "Yo're so ugly, when your mom dropped you off at school she got a fine for littering.",
  "Don't you love nature, despite what it did to you?",
  "You must have been born on a highway because that's where most accidents happen.",   "The only way you'll ever get laid is if you crawl up a chicken's ass and wait.",
  "It's better to let someone think you are an Idiot than to open your mouth and prove it.",
  "Keep talking, someday you'll say something intelligent!",
  "If you really want to know about mistakes, you should ask your parents.",
  "I wasn't born with enough middle fingers to let you know how I feel about you.",
  "What language are you speaking? Cause it sounds like bullshit.",
  "If I had a face like yours, I'd sue my parents.",
  "If laughter is the best medicine, your face must be curing the world.",
  "You so ugly when who were born the doctor threw you out the window and the window threw you back.",
  "You're so ugly, you scared the crap out of the toilet.",  "Roses are red violets are blue, God made me pretty, what happened to you?",
  "You're the reason the gene pool needs a lifeguard.",
  "Hey, you have something on your chin... no, the 3rd one down.",
  "I love what you've done with your hair. How do you get it to come out of the nostrils like that?",
  "You do realize makeup isn't going to fix your stupidity?",
  "We all sprang from apes, but you didn't spring far enough.",
  "Which sexual position produces the ugliest children? Ask your mother.",
  "If bullshit could float...you'd be the Admiral of the fleet! ",
  "Ever since I saw you in your family tree I've wanted to cut it down.",
  "You're so fake, Barbie is jealous.",  "You are proof that evolution CAN go in reverse.",
  "Ordinarily people live and learn. You just live.",
  "Do you wanna lose ten pounds of ugly fat? Cut off your head.",
  "I'm jealous of all the people that haven't met you!",
  "Aha, I see the Fuck-Up Fairy has visited us again! ",
  "So, a thought crossed your mind? Must have been a long and lonely journey.",
  "There's only one problem with your face, I can see it.",
  "Karma takes too long, I'd rather beat the shit out of you just now.",
  "Whats the difference between your girlfriend and a walrus? One has a moustache and smells of fish and the other is a walrus.",
  "It looks like your face caught on fire and someone tried to put it out with a hammer.",  "As an outsider, what do you think of the human race?",
  "I'm glad to see you're not letting your education get in the way of your ignorance.",
  "Support bacteria - they're the only culture some people have.",
  "I don't know what makes you so stupid, but it really works.",
  "Calling you an idiot would be an insult to all stupid people.",
  "I don't think you are stupid. You just have a bad luck when thinking.",
  "I'd like to see things from your point of view, but I can't seem to get my head that far up your ass.",
  "I would ask you how old you are but I know you can't count that high.",
  "You look like a before picture.",
  "You are so ugly when you looked in the mirror your reflection walked away......You are so ugly when you looked in the mirror your reflection walked away.You are so ugly when you looked in the mirror your reflection walked away.You are so ugly when you looked in the mirror your reflection walked away.You are so ugly when you looked in the mirror your reflection walked away.You are so ugly when you looked in the mirror your reflection walked away.You are so ugly when you looked in the mirror your reflection walked away.You are so ugly when you looked in the mirror your reflection walked away.You are so ugly when you looked in the mirror your reflection walked away."
];